### ISSUE TITLE
Missing info/items on the BOM

### ISSUE THREAD

**Issue by cskoven** [Jerzeek/PrintCam-Hardware#1]
Dear Jerry de Vos,

Thanks for putting this on github!
I've already gotten the PCBs produced for the stealth version.
Now I just need to get the rest of the items and assemble it.

I assume I need 1 of each of "SFH11-PBPC-D07-ST-BK" and "SBH11-PBPC-D07-ST-BK", and 2 of "RS1-08-G".
But from the picture (https://github.com/Jerzeek/PrintCam-Hardware/blob/main/media/stealth.jpg),
it seems I also need a 6pin-female header and a 2pin-male header.?

Is any other components missing?

Looking forward to get it up and running :)

Br,
Christian Skoven

**Comment by Jerzeek** [comment]
Hi Christian,
It is not required, it is optional. If you want to program the ESP in a simple way you can add the 6 pin female header, and then you can directly connect an [FTDI module](https://www.google.com/search?sca_esv=6b8c054c18cccfdb&sxsrf=ADLYWIIMVJp7iw6uN1q5zuVg0Z94YUFROg:1727942680921&q=ftdi+module&udm=2&fbs=AEQNm0Aa4sjWe7Rqy32pFwRj0UkWd8nbOJfsBGGB5IQQO6L3J_TJ4YMS4eRay1mUcjRHkZwkNnuzbvXdHSnZt8SI-ypebpRXuYkgug6DK-4Ut13H99ktA8Mqi1OEFqdR-eK48bJa__90OMgplgEoZnWValhUQ343gp_exU8Evdjtace2RF7oLL9h99qRkTgUJWLIWwzoXToL&sa=X&ved=2ahUKEwiB28CN4PGIAxUV7AIHHSVaMlsQtKgLegQIFhAB&biw=1512&bih=778&dpr=2#vhid=BuR7iyFjdxAqHM&vssid=mosaic) to it. The 2 pin male connector is the connected to the gpio0 pin, if you put a jumper on the 2 pin male header, it goes in bootloader mode.
I hope this helps!
